#!/bin/bash

fastmail_username=$(op read "op://Levain/unc5pppwakewyvnqro7size6rm/username")
fastmail_dav_password=$(op read "op://Levain/unc5pppwakewyvnqro7size6rm/u6uzhq7gnz5nyt2egdhxnsld3i")
fastmail_api_token=$(op read "op://Levain/unc5pppwakewyvnqro7size6rm/api token")

sudo tee ".envrc" > /dev/null <<EOF
export FASTMAIL_USERNAME=$fastmail_username
export FASTMAIL_DAV_PASSWORD=$fastmail_dav_password
export FASTMAIL_API_TOKEN=$fastmail_api_token
EOF
direnv allow .
