name: Collect stats

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-reports:
    runs-on: ubuntu-latest
    env: 
      FASTMAIL_API_TOKEN: ${{ secrets.FASTMAIL_API_TOKEN }}
      LOG_LEVEL: 'debug'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx ts-node src/count.ts
      - run: git add .
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: |
            Update stats for ${{ steps.date.outputs.date }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main