name: Collect reports

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  collect-reports:
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GIT_PUSH_TOKEN }}
      FASTMAIL_PASSWORD: ${{ secrets.FASTMAIL_PASSWORD }}
      LOG_LEVEL: 'debug'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: node index.js
      - run: git add .
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: |
            Update stats for ${{ steps.date.outputs.date }}
      - run: gh repo sync